//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string appointment_date { get; set; }
        public string appointment_time { get; set; }
        public Nullable<long> datetime_filter { get; set; }
        public string next_task { get; set; }
        public string addition_date { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
