//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationCharge
    {
        public int id { get; set; }
        public Nullable<int> prescription_id { get; set; }
        public Nullable<int> surgeon_charge { get; set; }
        public Nullable<int> assisstant_charge { get; set; }
        public Nullable<int> ot_charge { get; set; }
        public Nullable<int> suction_tube { get; set; }
        public Nullable<int> gloves { get; set; }
        public Nullable<int> sterilization_cost { get; set; }
        public Nullable<int> needle { get; set; }
        public Nullable<int> remar_file { get; set; }
        public Nullable<int> bar { get; set; }
        public Nullable<int> polishing_bar { get; set; }
        public Nullable<int> polishing_paste { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
