//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultedTreatment
    {
        public int id { get; set; }
        public Nullable<int> consultation_id { get; set; }
        public Nullable<int> treatment_id { get; set; }
        public string upper_left { get; set; }
        public string upper_right { get; set; }
        public string lower_left { get; set; }
        public string lower_right { get; set; }
    
        public virtual Treatment Treatment { get; set; }
        public virtual Consultation Consultation { get; set; }
    }
}
