//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public Consultation()
        {
            this.ConsultedTreatments = new HashSet<ConsultedTreatment>();
        }
    
        public int id { get; set; }
        public Nullable<int> prescription_id { get; set; }
        public string consultation_date { get; set; }
        public Nullable<int> payment_recieved { get; set; }
    
        public virtual Prescription Prescription { get; set; }
        public virtual ICollection<ConsultedTreatment> ConsultedTreatments { get; set; }
    }
}
