//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public Prescription()
        {
            this.ConsultationCharges = new HashSet<ConsultationCharge>();
            this.Consultations = new HashSet<Consultation>();
            this.PrescribedTreatments = new HashSet<PrescribedTreatment>();
        }
    
        public int id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string prescription_date { get; set; }
        public string oral_examination { get; set; }
        public string medical_history { get; set; }
        public string investigation { get; set; }
        public string advice { get; set; }
    
        public virtual ICollection<ConsultationCharge> ConsultationCharges { get; set; }
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PrescribedTreatment> PrescribedTreatments { get; set; }
    }
}
