//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmileMakersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.ConsultedTreatments = new HashSet<ConsultedTreatment>();
            this.PrescribedTreatments = new HashSet<PrescribedTreatment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<ConsultedTreatment> ConsultedTreatments { get; set; }
        public virtual ICollection<PrescribedTreatment> PrescribedTreatments { get; set; }
    }
}
